from __future__ import annotations

import argparse
import json
import platform
from dataclasses import asdict
from pathlib import Path
from shutil import disk_usage

from iot_ids.data.adapters import build_default_adapters
from iot_ids.utils.paths import resolve_repo_path


def capture_environment(data_root: Path) -> dict[str, object]:
    usage = disk_usage(data_root.anchor or ".")
    return {
        "platform": platform.platform(),
        "python": platform.python_version(),
        "processor": platform.processor(),
        "logical_cpus": __import__("os").cpu_count(),
        "disk_total_bytes": usage.total,
        "disk_free_bytes": usage.free,
        "data_root": str(data_root),
    }


def write_markdown(audits: list[dict[str, object]], environment: dict[str, object], output: Path) -> None:
    lines = [
        "# Initial Dataset Audit",
        "",
        "Generated by `scripts/audit_datasets.py`.",
        "",
        "## Environment",
        "",
    ]
    for key, value in environment.items():
        lines.append(f"- `{key}`: `{value}`")
    lines.extend(["", "## Dataset Status", ""])

    for audit in audits:
        lines.append(f"### {audit['name']}")
        lines.append("")
        lines.append(f"- status: `{audit['status']}`")
        lines.append(f"- root: `{audit['root']}`")
        lines.append(f"- files: `{audit['total_files']}`")
        lines.append(f"- total size bytes: `{audit['total_size_bytes']}`")
        lines.append(f"- source files under root: `{audit.get('source_total_files', audit['total_files'])}`")
        lines.append(
            f"- source total size bytes: `{audit.get('source_total_size_bytes', audit['total_size_bytes'])}`"
        )
        row_counts = [
            file_profile.get("row_count")
            for file_profile in audit["files"]
            if file_profile.get("row_count") is not None
        ]
        if row_counts:
            lines.append(f"- total CSV rows: `{sum(row_counts)}`")
        labels = ", ".join(audit["label_columns_seen"]) or "none observed"
        leakage = ", ".join(audit["leakage_columns_seen"][:30]) or "none observed"
        temporal = ", ".join(audit["temporal_columns_seen"]) or "none observed"
        entity = ", ".join(audit["entity_columns_seen"]) or "none observed"
        lines.append(f"- label candidates: {labels}")
        lines.append(f"- leakage candidates: {leakage}")
        lines.append(f"- temporal candidates: {temporal}")
        lines.append(f"- entity candidates: {entity}")
        if audit.get("label_distribution"):
            lines.append("- label distribution:")
            for column, counts in audit["label_distribution"].items():
                preview = ", ".join(f"{k}={v}" for k, v in list(counts.items())[:20])
                lines.append(f"  - `{column}`: {preview}")
        if audit["notes"]:
            lines.append("- notes:")
            lines.extend(f"  - {note}" for note in audit["notes"])
        lines.append("")

    output.write_text("\n".join(lines) + "\n", encoding="utf-8")


def run_audit(data_root: Path, output: Path, sample_rows: int) -> list[dict[str, object]]:
    output.mkdir(parents=True, exist_ok=True)
    adapters = build_default_adapters(data_root, sample_rows=sample_rows)
    audits = [asdict(adapter.audit()) for adapter in adapters]
    environment = capture_environment(data_root)

    (output / "dataset_audit.json").write_text(
        json.dumps({"environment": environment, "datasets": audits}, indent=2),
        encoding="utf-8",
    )
    write_markdown(audits, environment, output / "dataset_audit.md")
    return audits


def main() -> None:
    parser = argparse.ArgumentParser(description="Audit P1 raw IoT IDS datasets.")
    parser.add_argument("--data-root", default="data/raw")
    parser.add_argument("--output", default="reports/eda")
    parser.add_argument("--sample-rows", type=int, default=5000)
    args = parser.parse_args()

    run_audit(
        data_root=resolve_repo_path(args.data_root),
        output=resolve_repo_path(args.output),
        sample_rows=args.sample_rows,
    )


if __name__ == "__main__":
    main()
